name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check_formatting:

    runs-on: ubuntu-latest
    name: Check Formatting & Test

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet tool restore
    - name: Run CSharpier
      run: dotnet csharpier --check ./src
    - name: Test
      run: dotnet test ./src